# SSO单点登录配置
sa-token:
  sso:
    # 是否是从单点登录1.0兼容而来，默认false
    compatible: false
    # sso-server前端访问地址
    auth-url: http://192.168.1.66:10001/index.html
    # sso-server后端接口地址
    server-url: http://192.168.1.65:10000/sso-server/
    # 业务系统标识 注：需登录认证中心-基础管理系统-权限管理-系统管理-（页签）单点登录-右侧按钮（详情）ServieCode
    servicecode: super_agent
    # 业务系统公钥 注：需登录认证中心-基础管理系统-权限管理-系统管理-（页签）单点登录-右侧按钮（详情）公钥
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVawc26t6JxZnnn5yhAYfbrlNcx4lq/oB5Wy6SKdKDcj2Cfk2L/cPeo7+fNtZAtJBnOU3jUp3aQ+RPdSh8X+NU4zH50655Ey7bH73QJbfTnUtquIVbX/1E2/VTV0wOuFrq/pQ2UVDWcAluJtiZkp+cdNqJqEN3JPm0dQ/X2U/n9QIDAQAB
    # 加密用户登录密码的公钥
    sm2-key: 04a5e22ae1d17350b3b33e849f74e0b15ac4a47a5af825a61b8181825cf34219507232b3f3844c62884c4ecf27876a89c94d6e25912e552774d9c4791a705e5dc5
    # 业务系统不需要认证的地址路径
    exclude-urls: [
      "/sso/*",
      "favicon.ico",
      "/**/*.css",
      "/**/*.html",
      "/**/*.js",
      # Swagger API文档相关
      "swagger-resource",
      "/v3/api-docs/**",
      "/v3/api-docs/swagger-config",
      "/doc.html/**",
      "/webjars/**",
      "/swagger-ui.html",
      "/swagger-ui/**",
      "/swagger-resources/**",
      "/v2/api-docs",
      # 认证相关接口（用户登录前需要访问）
      "/api/v1/auth/send-sms",
      "/api/v1/auth/reset-password", 
      "/api/v1/auth/register",
      "/api/v1/auth/phone-login",
      "/api/v1/auth/password-login",
      "/api/v1/auth/get-sys-client-info",
      "/api/v1/auth/public-key",
      # SSO代理接口（处理SSO认证流程，不应被拦截）
      "/sso/doLoginByTicket",
      # 静态资源
      "/chat.html",
      "/static/**",
      "/api/v1/resource-usage/report",
      "/api/v1/**"
    ]
    isHttp: true
  # Token超时配置（控制您系统中satoken的有效期）
  # token有效期，单位s 默认30天, -1代表永不过期  
  timeout: 2592000
  # token临时过期时间 (指定时间内无操作就视为token过期) 单位: 秒, -1代表不限制
  activity-timeout: 1800
  # 是否打印启动成功标志
  is-print: true
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录) =-1
  isConcurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  isShare: false
  # 是否使用redis存储信息，默认false使用内存来存储信息，true使用spring redis存储信息（请配置spring redis），若配置下述alone-redis，则使用下述alone-redis存储信息（不必再配置spring redis）。
  redis-enabled: true
  alone-redis:
    # 是否启用独立的redis来存储信息，此处为true时，redis-enabled也要设置为true
    enabled: true
    # cluster:
    #   nodes: 192.168.5.160:6379,192.168.5.161:6379,192.168.5.162:6379
    # password: zb@123
    host: 192.168.1.66
    port: 6379
    database: 1
    connect-timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0