# ========== MyBatis-Flex 配置 ==========
mybatis-flex:
  # Mapper XML文件位置
  mapper-locations: classpath*:/mapper/*.xml
  # 实体类包名
  type-aliases-package: com.noah.superagent.dao.entity
  # MyBatis配置
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    # 关闭二级缓存
    cache-enabled: false
    # 延迟加载
    lazy-loading-enabled: false
    # 积极的延迟加载
    aggressive-lazy-loading: false
    # 是否允许单一语句返回多结果集
    multiple-result-sets-enabled: true
    # 使用列标签代替列名
    use-column-label: true
    # 使用生成的键
    use-generated-keys: false
    # 自动映射策略
    auto-mapping-behavior: partial
    # 自动映射未知列行为
    auto-mapping-unknown-column-behavior: none
    # 默认执行器类型
    default-executor-type: simple
    # 默认语句超时时间
    default-statement-timeout: 25000
    # 默认获取数据大小
    default-fetch-size: 100
    # 允许在嵌套语句中使用分页
    safe-row-bounds-enabled: false
    # 本地缓存机制
    local-cache-scope: session
    # JDBC类型空值处理
    jdbc-type-for-null: other
    # 延迟加载触发方法
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    # 默认脚本语言
    default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
    # 是否调用setter方法或map的put方法
    call-setters-on-nulls: false
    # 返回实例时是否返回空实例
    return-instance-for-empty-row: false
    # 日志前缀
    log-prefix: 
    # 日志实现
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 代理工厂
    proxy-factory: org.apache.ibatis.executor.loader.javassist.JavassistProxyFactory
